from typing import Protocol, Optional
from app.domain.models import Payment, Refund


class PaymentRepositoryProtocol(Protocol):
    async def create(self, payment: Payment) -> Payment: ...
    async def find_by_id(self, payment_id: str) -> Optional[Payment]: ...
    async def find_by_order(self, order_id: str) -> Optional[Payment]: ...
    async def update_status(self, payment_id: str, status: str, transaction_id: Optional[str] = None) -> None: ...
    async def update_retry(self, payment_id: str, retry_count: int, failure_reason: str) -> None: ...
    async def create_refund(self, refund: Refund) -> Refund: ...
    async def find_refunds_by_payment(self, payment_id: str) -> list[Refund]: ...


class EventProducerProtocol(Protocol):
    async def publish(self, topic: str, key: str, value: dict) -> None: ...
