export const PRODUCT_EVENTS_TOPIC = 'product-events';

export enum ProductEventType {
  PRODUCT_CREATED = 'PRODUCT_CREATED',
  PRODUCT_UPDATED = 'PRODUCT_UPDATED',
  PRODUCT_DELETED = 'PRODUCT_DELETED',
  PRICE_CHANGED = 'PRICE_CHANGED',
}
