from typing import Protocol, Optional
from app.domain.models import User, Address


class UserRepositoryProtocol(Protocol):
    async def create(self, user: User) -> User: ...
    async def find_by_id(self, user_id: str) -> Optional[User]: ...
    async def find_by_email(self, email: str) -> Optional[User]: ...
    async def find_all(self, limit: int = 50, offset: int = 0) -> list[User]: ...
    async def update(self, user: User) -> User: ...
    async def delete(self, user_id: str) -> bool: ...
    async def create_address(self, address: Address) -> Address: ...
    async def find_addresses_by_user(self, user_id: str) -> list[Address]: ...
    async def delete_address(self, address_id: str) -> bool: ...


class EventProducerProtocol(Protocol):
    async def publish(self, topic: str, key: str, value: dict) -> None: ...
