from typing import Protocol, Optional
from app.domain.models import Order, SagaStep


class OrderRepositoryProtocol(Protocol):
    async def create(self, order: Order) -> Order: ...
    async def find_by_id(self, order_id: str) -> Optional[Order]: ...
    async def find_by_user(self, user_id: str) -> list[Order]: ...
    async def update_status(self, order_id: str, status: str) -> None: ...
    async def update_saga_status(self, order_id: str, saga_status: str) -> None: ...
    async def save_saga_step(self, step: SagaStep) -> SagaStep: ...
    async def update_saga_step(self, step_id: str, status: str, response: dict) -> None: ...


class EventProducerProtocol(Protocol):
    async def publish(self, topic: str, key: str, value: dict) -> None: ...
