from typing import Protocol, Optional
from app.domain.models import Cart, CartItem


class CartRepositoryProtocol(Protocol):
    async def create(self, cart: Cart) -> Cart: ...
    async def find_by_id(self, cart_id: str) -> Optional[Cart]: ...
    async def find_by_user(self, user_id: str) -> Optional[Cart]: ...
    async def add_item(self, item: CartItem) -> CartItem: ...
    async def update_item_quantity(self, item_id: str, quantity: int) -> None: ...
    async def remove_item(self, item_id: str) -> bool: ...
    async def apply_coupon(self, cart_id: str, coupon_code: str, discount: float) -> None: ...
    async def clear_cart(self, cart_id: str) -> None: ...
    async def update_status(self, cart_id: str, status: str) -> None: ...


class EventProducerProtocol(Protocol):
    async def publish(self, topic: str, key: str, value: dict) -> None: ...


class CacheProtocol(Protocol):
    async def get(self, key: str) -> Optional[str]: ...
    async def set(self, key: str, value: str, ttl: Optional[int] = None) -> None: ...
    async def delete(self, key: str) -> None: ...
