from typing import Protocol, Optional
from app.domain.models import Product, Category, ProductReview


class ProductRepositoryProtocol(Protocol):
    async def create(self, product: Product) -> Product: ...
    async def find_by_id(self, product_id: str) -> Optional[Product]: ...
    async def find_all(self, limit: int = 50, offset: int = 0) -> list[Product]: ...
    async def find_by_category(self, category_id: str) -> list[Product]: ...
    async def search(self, query: str) -> list[Product]: ...
    async def update(self, product: Product) -> Product: ...
    async def delete(self, product_id: str) -> bool: ...
    async def create_category(self, category: Category) -> Category: ...
    async def find_all_categories(self) -> list[Category]: ...
    async def create_review(self, review: ProductReview) -> ProductReview: ...
    async def find_reviews_by_product(self, product_id: str) -> list[ProductReview]: ...


class CacheProtocol(Protocol):
    async def get(self, key: str) -> Optional[str]: ...
    async def set(self, key: str, value: str, ttl: Optional[int] = None) -> None: ...
    async def delete(self, key: str) -> None: ...


class EventProducerProtocol(Protocol):
    async def publish(self, topic: str, key: str, value: dict) -> None: ...
