export const INVENTORY_EVENTS_TOPIC = 'inventory-events';

export enum InventoryEventType {
  INVENTORY_RESERVED = 'INVENTORY_RESERVED',
  INVENTORY_RELEASED = 'INVENTORY_RELEASED',
  INVENTORY_RESERVATION_FAILED = 'INVENTORY_RESERVATION_FAILED',
  LOW_STOCK_ALERT = 'LOW_STOCK_ALERT',
}
