from typing import Protocol, Optional
from datetime import date
from app.domain.models import Event, Metric, DailyAggregation


class AnalyticsRepositoryProtocol(Protocol):
    async def save_event(self, event: Event) -> Event: ...
    async def get_events(self, event_type: Optional[str] = None, limit: int = 100) -> list[Event]: ...
    async def save_metric(self, metric: Metric) -> Metric: ...
    async def get_metrics(self, metric_name: Optional[str] = None) -> list[Metric]: ...
    async def get_daily_aggregation(self, target_date: date) -> Optional[DailyAggregation]: ...
    async def save_daily_aggregation(self, agg: DailyAggregation) -> DailyAggregation: ...
