from enum import Enum


class ProductEvent(str, Enum):
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_DELETED = "PRODUCT_DELETED"
    REVIEW_ADDED = "REVIEW_ADDED"
