from typing import Protocol, Optional
from app.domain.models import InventoryItem, Reservation


class InventoryRepositoryProtocol(Protocol):
    async def create(self, item: InventoryItem) -> InventoryItem: ...
    async def find_by_product(self, product_id: str) -> Optional[InventoryItem]: ...
    async def find_all(self) -> list[InventoryItem]: ...
    async def update_quantity(self, product_id: str, quantity: int) -> None: ...
    async def reserve_stock(self, product_id: str, quantity: int) -> bool: ...
    async def release_stock(self, product_id: str, quantity: int) -> None: ...
    async def confirm_reservation(self, product_id: str, quantity: int) -> None: ...
    async def create_reservation(self, reservation: Reservation) -> Reservation: ...
    async def find_reservations_by_order(self, order_id: str) -> list[Reservation]: ...
    async def update_reservation_status(self, reservation_id: str, status: str) -> None: ...


class EventProducerProtocol(Protocol):
    async def publish(self, topic: str, key: str, value: dict) -> None: ...
